version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: grouple-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - grouple-network

volumes:
  mysql_data:

networks:
  grouple-network:
    driver: bridge
