version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: grouple-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - grouple-network

  redis:
    image: redis:7-alpine
    container_name: grouple-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - grouple-network

volumes:
  mysql_data:
  redis_data:

networks:
  grouple-network:
    driver: bridge
